# Adapted from https://github.com/iloveitaly/asdf-devcontainer/blob/main/Dockerfile
# This needs to be run at the root repo context, because it's caching dependencies
# based on files at that level
FROM mcr.microsoft.com/vscode/devcontainers/base:1.1.5-ubuntu24.04

# needs to be declared *after* FROM to be available in shell scripts
# renovate: datasource=github-releases depName=asdf packageName=asdf-vm/asdf
ARG ASDF_VERSION=v0.14.1

LABEL org.opencontainers.image.authors="Dang Mai <contact@dangmai.net>" \
      org.opencontainers.image.source=https://github.com/dangmai/prettier-plugin-apex \
      org.opencontainers.image.licenses="MIT" \
      org.opencontainers.image.title="Prettier Apex Devcontainer Image" \
      org.opencontainers.image.description="A Docker image for use with VS Code's Remote Containers extension or GitHub codespaces."

USER vscode
RUN git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch ${ASDF_VERSION}

# including the asdf source in sh + bash profiles make it easier to run boostrap scripts
# which expect `asdf` to be available
RUN echo "\n. $HOME/.asdf/asdf.sh\n" | tee -a ~/.bashrc ~/.profile

COPY --chown=vscode:vscode .tool-versions /home/vscode/.tool-versions
ENV PATH=$PATH:/home/vscode/.asdf/bin:/home/vscode/.asdf/shims
WORKDIR /home/vscode
RUN cat .tool-versions | cut -d' ' -f1 | grep "^[^\#]" | xargs -i asdf plugin add {} && asdf install
RUN gu install native-image
RUN corepack enable
RUN asdf reshim nodejs
RUN pnpm completion bash > ~/completion-for-pnpm.bash
RUN echo 'source ~/completion-for-pnpm.bash' >> ~/.bashrc
