#!/usr/bin/env -S tsx
//
// Deterministically generates a large, valid Apex class used as the "stress"
// input for the performance harness. The real test fixtures are small (~hundreds
// of lines), which in native mode are dominated by process startup and leave the
// prepping/printing buckets in the noise floor. This synthesized class is big
// enough that those buckets become measurable and regression-detectable.
//
// Output is a pure function of METHOD_COUNT (no randomness, no timestamps) so the
// checked-in file is stable and reviewable. Re-run with:
//   pnpm tsx tests_perf/generate-corpus.ts
//
import { writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const METHOD_COUNT = 130; // ~4k lines

function generateMethod(i: number): string {
  const limit = (i % 50) + 1;
  const factor = (i % 7) + 1;
  return `  public Decimal computeValue${i}(Integer base, String label) {
    Decimal total = ${i}.0;
    List<Account> accounts = [
      SELECT Id, Name, AnnualRevenue, (SELECT Id FROM Contacts)
      FROM Account
      WHERE Name = :label AND AnnualRevenue > ${i * 100}
      ORDER BY Name ASC, AnnualRevenue DESC
      LIMIT ${limit}
    ];
    for (Account acct : accounts) {
      if (acct.AnnualRevenue != null && acct.AnnualRevenue > ${i}) {
        total += acct.AnnualRevenue * ${factor};
      } else if (acct.Name != null) {
        total -= base;
      } else {
        total = total + 1;
      }
    }
    Integer adjusted = base > 0 ? base * ${i + 1} : ${i};
    Map<String, Integer> counters = new Map<String, Integer>{
      'first' => ${i},
      'second' => ${i + 1},
      'third' => adjusted
    };
    String message =
      'Computed ' + label + ' = ' + String.valueOf(total + adjusted);
    System.debug(LoggingLevel.INFO, message + ' counters=' + counters.size());
    return total + adjusted;
  }`;
}

function generateClass(): string {
  const methods = Array.from({ length: METHOD_COUNT }, (_, i) =>
    generateMethod(i),
  ).join("\n\n");
  return `// Auto-generated by tests_perf/generate-corpus.ts. Do not edit by hand.
// Regenerate with: pnpm tsx tests_perf/generate-corpus.ts
public class PerfBenchmarkLarge {
${methods}
}
`;
}

const outPath = path.join(
  path.dirname(fileURLToPath(import.meta.url)),
  "corpus",
  "PerfBenchmarkLarge.cls",
);
writeFileSync(outPath, generateClass(), "utf8");
console.log(`Wrote ${outPath}`);
