class ExtendImplementClass extends FirstExtend implements FirstImplement, SecondImplement {
  public virtual class VirtualExtendInnerClass extends FirstExtend {


  }

  private abstract class AbstractImplementInnerClass implements FirstImplement {

  }

  global class ExtendImplementInnerClass extends FirstExtend implements FirstImplement, SecondImplement {

  }

  public override Integer compareTo(Object anotherObject) {

  }
}
