class SharingClass {
  public with sharing class PublicWithSharingClass {

  }

  private without sharing class PrivateWithoutSharingClass {

  }

  global without sharing class GlobalWithoutSharingClass {

  }

  virtual with sharing class VirtualWithSharingClass {

  }

  abstract with sharing class AbstractWithSharingClass {

  }
  without sharing class WithoutSharingClass {

  }
  with sharing class WithSharingClass {}
}
